/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#d3daef',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8fd',
        'surface-container-highest': '#dce2f7',
        'on-surface': '#141b2b',
        'on-surface-variant': '#534434',
        'inverse-surface': '#293040',
        'inverse-on-surface': '#edf0ff',
        outline: '#867461',
        'outline-variant': '#d8c3ad',
        'surface-tint': '#855300',
        primary: '#855300',
        'on-primary': '#ffffff',
        'primary-container': '#f59e0b',
        'on-primary-container': '#613b00',
        'inverse-primary': '#ffb95f',
        secondary: '#0058be',
        'on-secondary': '#ffffff',
        'secondary-container': '#2170e4',
        'on-secondary-container': '#fefcff',
        tertiary: '#006e2f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2bca62',
        'on-tertiary-container': '#004f20',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffddb8',
        'primary-fixed-dim': '#ffb95f',
        'on-primary-fixed': '#2a1700',
        'on-primary-fixed-variant': '#653e00',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'tertiary-fixed': '#6bff8f',
        'tertiary-fixed-dim': '#4ae176',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005321',
        background: '#f9f9ff',
        'on-background': '#141b2b',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
        14: '14px',
      },
      spacing: {
        'container-max': '1440px',
        'gutter': '24px',
        'margin-page': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
      boxShadow: {
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
      }
    },
  },
  plugins: [],
}
